export const emojis = {
    'aftrican_elephant': '🐘',
    'african_wild dog': '🐕',
    'africanforestelephant': '🐘',
    'africansavannaelephant': '🐘',
    'albacore_tuna': '🐟',
    'amazon_river dolphin': '🐬',
    'amur_leopard': '🐆',
    'arctic_fox': '🦊',
    'arctic_wolf': '🐺',
    'asian_elephant': '🐘',
    'beluga': '🐋',
    'bigeye_tuna': '🐟',
    'black_-footed ferret': '🐭',
    'black_rhino': '🦏',
    'black_spider monkey': '🐒',
    'blue_whale': '🐋',
    'bluefin_tuna': '🐟',
    'bonobo': '🦍',
    'bornean_elephant': '🐘',
    'bornean_orangutan': '🦧',
    'bowhead_whale': '🐋',
}